posco:
    name: 3기dev
    count: 20
    datasource:
        url: jdbc:mysql://?.?.?.?:3306/insta?serverTimezone=UTC&amp
        characterEncoding: UTF-8
        username: root
        password: 1234
spring:
    datasource:
        url: jdbc:mysql://?.?.?.?:3306/insta?serverTimezone=UTC&amp
        characterEncoding: UTF-8
        username: root
        password: "1234"


jwt:
  secret_key: SECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEY
  expTime : 86400000