jwt:
    time: 900000
    secret: hello-world4444
posco:
    name: 3기dev
    count: 20
    datasource:
        url: jdbc:mysql://localhost:3306/insta?serverTimezone=UTC&amp
        characterEncoding: UTF-8
        username: root
        password: 1234
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/insta?serverTimezone=UTC&amp
        characterEncoding: UTF-8
        username: root
        password: "{cipher}de57929d157783fcfbf1f4829688829bfac4f8de4f57bcd194e4c475ee99936f"